resources/av-warehouse/config.lua

- Added Musket Ammo
- Changed the iron oxide to drop in 2 packs of 5

Warehouse drops update

---

resources/usa_mining/server/server.lua

I adjusted the prices for all the ores to try and increase the amount of Civilians whom like to make more money for their hard work at Mining

Adjustment(Mining): Slight Pay Increase

---

resources/usa_gunonback/cl_weapons-on-back.lua

Changed position slightly and commented out jerry can because bulletproof

Position adjustment to weapons on back

---

resources/usa_hunting/server/server.lua

I'm submitting this change since I believe that Hunting should have a little more reward for the hard work you have to do during this job.

(Hunting): Raised prices for fur and meat

---

resources/usa_selldrugs/server.lua

I'm submitting a price increase of blue meth since you have that slight chance of blowing up while cooking. So that make the item a little more rare then your easy to make drug. That's why I believe this price change is needing.

Adjustment (Blue Meth)

---

resources/_weaponrealism/cl_weapon-realism.lua

Removed camera shake - this only affected the people outside of cars - Made it unfair for people fighting on foot
Lowered the car inaccuracy pitch - this only affects 3rd person shooting especially from helicopters meaning you shoot once you would aim at the ground/sky
Overall everything got lowered a little and should make gunfights smoother
I might do dmg changes later down the road in case its needed

Recoil update

---

resources/es_admin/sv_admin.lua

- Created a `/goto mrpd` command, due to us already having a `/goto pd` which goes to the police department in paleto, and also a `/goto fd` which goes to the fire department in paleto. Having one that goes to MRPD would be beneficial, as it just makes our lives as staff easier if we need to go to MRPD for something, such as clocking in, or going back to the PD after handling something staff related. The current coords for this takes us on the roof `https://i.imgur.com/A5o8hZV.jpeg`

Updated sv_admin.lua

---

resources/usa-pilotjob/sv_pilotjob.lua

Upped the price of each job individually as per @Bobby's request. Overall, the job pays too little anyways compared to trucking or dock container job, which both should technically pay less than a pilot.

Increased Pilot Job Pay

---

resources/usa_chopshop/sv_chopshop.lua

Upped the reward amount max to 1250 and increased the percent reward if no cops from 20% of reward to 25%.

Slight Increase on Chop Payout

---

resources/usa_toggleclothes/cl_toggleclothing.lua

Fixed /shoe for male and female

shoe toggle fix

---

resources/usa_fishing/sv_fishing.lua

I'm submitting a price increase on fishing to bring more attention to the legal side of the city.

Fishing Price Increase

---

resources/av-warehouse/server/main.lua

Removed warehouse location `10` as it caused issued whenever entering/leaving. @PickleRick can also confirm, and it always happens to me too

Updated Warehouse main.lua

---

server.cfg

Disable motorbike MLO behind courthouse

Disable useless MLO

---

resources/usa_paycheck/paycheck_sv.lua

- Renamed BCSO Rank 3 comment to `Probational Deputy` as it was still `Correctional Corporal`

Updated paycheck_sv.lua

---

resources/usa_garage/client.lua

Added a garage location to La Mesa PD so officers can store vehicles without having to walk for away to another location.
(Requested by @Crownapple)

feat(Garage): La Mesa PD Location

---

resources/character-selection/character-creation_cl.lua

Fixed LS Spawn

---

resources/usa_rp2/sv_police.lua

Added a panic button for doctors as it was requested by @Derangedconch43.

feat(Jobs): Panic button for Doctors

---

resources/usa_prison/contraband/sv_contraband.lua

Added phone as possible prison drop

Updated sv_contraband.lua

---

resources/usa_govfunding/sv_govfunding.lua

- Changed the minimum rank required from Sr. Deputy to Captain | It should've been Captain already, however due to the change in ranks and all of that, it got moved over but never updated | I have asked Colt about the rank that it should've been set to, and I have changed it around for him.
Colt's Message: https://i.imgur.com/IjxXJr4.png
Current ranking structure: https://i.imgur.com/s9NYrNy.png

Changed BCSO's govfunding rank

---

resources/usa_stores/sv_generalstore.lua

2 people decided to abuse it to get to places they shouldn't be

Removed beer pong from prison

---

resources/usa_aircraftshop/sv_airshop.lua

Changed the parachute weight from 15 to 8.

change(Shops): Parachute Weight

---

resources/usa_police/server.lua

Usage: /records ID
The Idea behind this was for cops to be able to pull vehicle records without having to contact a staff member to do it.
**Command is only temp as I will be adding this to the Person Search in the MDT.**

feat(Police): Get Vehicle Records CMD

---

resources/_weaponrealism/cl_weapon-realism.lua

Still added some kick to the weapons, but not as insane as if you are in a vehicle 😄

Adjusted recoil while in a heli

---

resources/usa_police/server.lua

When typing /records it will now show the information needed for the command.

update(Police): Added ID Params to Records CMD

---

resources/usa_police/server.lua

Removed unused code from the command

update(Police): Records CMD Code Cleanup

---

resources/[orange-picking]/Burevestnik_orangejob/server.lua
resources/[orange-picking]/Burevestnik_orangejob_lib/server.lua
resources/usa_rp2/ITEMS.lua

update(Oranges): Oranges Now Consumable

---

resources/usa_mechanicjob/mechanic_cl.lua

This should fix the issue with vehicles not going onto the tow truck bed sometimes when typing /tow.

fix(Towing): Tow Vehicles Fix

---

resources/[orange-picking]/Burevestnik_orangejob/server.lua
resources/[orange-picking]/Burevestnik_orangejob_lib/server.lua

Changed the orange substance from 5 to 35

update(Oranges): Updated Orange Substance

---

resources/erp_adminmenu/server/discord.lua
resources/usa_automsg/cl_messages.lua
resources/usa_rp2/server.lua

Ever wanted to provide feedback about the server to the staff team? You can do so by typing /feedback message in chat!
You can only use the command once per server restart.
Usage: /feedback message
Issue: #866 Completed

feat(Commands): Feedback CMD

---

README.md

Added the new feedback command & Admin Menu convars

Updated Readme with new convars

---

resources/kq_wheeldamage/config.lua

Changed all the damage values so wheels don't fall off as easy.

update(WheelDamage): Updated Damage Values

---

resources/usa_vehtheft/__resource.lua
resources/usa_vehtheft/cl_hotwire.lua
resources/usa_vehtheft/fxmanifest.lua
resources/usa_vehtheft/html/index.html
resources/usa_vehtheft/html/main.css
resources/usa_vehtheft/html/scripts.js

update(Hotwiring): Added Minigame To Hotwiring

---

resources/usa_vehtheft/cl_hotwire.lua

Lowered hotwire kit break chance from 70% to 40%

lowered hotwire break chance

---

resources/usa_cuffs/cl_cuff.lua

Added another cuff cutting location.
Coords: 605.73565673828 -3091.7116699219 6.069260597229
Location is the one that was suggested at the docks.

update(Cuffs): 2nd Cuff Cut Location

---

resources/usa_dumpsters/client/client.lua

Increased the dumpster search time from 1.5 seconds to 10 seconds.
Requested by: @minipunch

update(Dumpsters): Increase Search Time

---

resources/usa-crafting/config.lua

Yo its zeero i just added 2 more crafting locations across the map and slightly changed the crafting time. "images below"
https://imgur.com/S9kdBfJ.png
https://imgur.com/Xhphd0L.png

2 New crafting locations & tweaked crafting time

---

resources/interaction-menu/cl_interaction.lua

Time increased from 2,6 - 5 seconds
Tweaked animation to look less fucky

First aid adjustments

---

resources/usa_stores/sv_generalstore.lua

Added tablets to hardware stores.
TESTED
https://i.imgur.com/6E9QALL.png
https://i.imgur.com/8kE4H8Z.png

Updated sv_generalstores.lua

---

resources/usa_garage/client.lua

Changed location of it due to causing ppl to be invisible. Tested, @minipunch was my witness

Updated RPG Garage

---

server.cfg

Added
- Forum (Bloods)
- Fudge (THF)
- Jamestown (Reapers)
- Triads (Not Taken)
- Naked Peeps
- Stabcity (Outlaws)
Removed numerous conflicting MLOs. Nothing big
Also removed some old useless MLOs from Gorys days

Map changes

---

resources/connectqueue/server/server.lua
server.cfg

Reduced the slots from 150 to 100 | Would look better when the server has like 70/100 rather than 70/150. Better for new players, makes the server look more full, and more appealing.
**COULDN'T TEST BECAUSE MY PC WOULD IMPLODE IF I WERE TO RUN A SERVER WITH 100 SLOTS!!!**

Reduced slots

---

resources/essentialmode/server/db.lua
resources/interaction-menu/cl_interaction.lua
resources/usa-characters/classes/character.lua
resources/usa_ammunition/__resource.lua
resources/usa_ammunition/client/cl_ammunition.lua
resources/usa_ammunition/server/sv_ammunition.lua

Make magazines optional

---

resources/usa_visualholster/client.lua

- Added more textures to some clothing
- Added Triads Racing chain (custom order)
- Fixed visual holster

Clothing update

---

resources/usa_stores/sv_generalstore.lua

Removed repair kit from hardware store

---

resources/[system]/globals/cl_global.lua
resources/interaction-menu/inventory/hotkeys/cl_hotkeys.lua

- Players are now able to use the 5th slot in their inventory with there number 5 key.
- Preview : https://streamable.com/hee7uc

New usable inventory slot

---

README.md

from resources/essentialmode/db.lua to resources\essentialmode\server\db.lua

corrected essential mode db.lua location in readme

---

resources/usa-crafting/config.lua

- fixed scar fn recipe giving u an akorus, should now give u a scar 
- fixed weight also from 25 to 28

Fixed scar issue

---

resources/usa_carshop/vehicle-shop_sv.lua

Raised price of the 
Lancer Evolution IX Voltex from 95,000 to 150,000
Murcielago LP-670 LW from 450,000 to 550,000
Murcielago LP-670 from 450,000 to 500,000

Adjusted Car shop

---

server.cfg

Disabled the pressure washer model

Optimizaaaations

---

resources/usa_chickenjob/sv_chickenjob.lua

Adjusted income based on amount of work required

Adjust Cluckin Bell

---

resources/usa_chickenjob/sv_chickenjob.lua

Bring some life back into Grinding for cash again

Chicken Job pay Increase

---

resources/usa_mining/server/server.lua

Try to boost the Players to bring back Grinding for money instead of only doing Art heist, Drugs, And the new jobs in the server.

Mining Update

---

resources/usa_hunting/server/server.lua

Try to bring back grinding again

Meat And Fur Changes

---

resources/usa_paycheck/paycheck_sv.lua

Trooper through to Director updated to match BCSO pay grades.

Updated SASP paychecks to match BCSO

---

resources/usa_paycheck/paycheck_sv.lua

Pay grades are higher for our medical and emergency medical staff! Promoting that EMS and Doctor RP appeal!

Update LSFD and Pillbox pay per A.Chris' request

---

resources/Sil-Vape/Config.lua

Changed the "VapeHangTime" to be a lot higher - we LOVE the smoke!
Upped the "Smoke Size" just a tad because yet again, we LOVE the smoke! 
#VapeNation!

Vape update 🚬

---

resources/usa_map_blips/client.lua

That is the name of the property, and the name filed under the Business prop.

Change "PDM Rockford Hills" Blip to "Luxury Autos"

---

resources/usa_foodservice/client/contextMenus.lua

It took me 10 minutes to make one order, I don't see this being tooooo realistic in the slightest 🥴 :(

Lower BurgerShot cooking times
